services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  php-my-admin:
    image: 'phpmyadmin:latest'
    restart: 'always'
    container_name: 'php-my-admin'
    ports:
      - 8081:80
    environment:        
      PMA_HOST: mysql
